### ISSUE TITLE
Is the VSCode extension outdated?

### ISSUE THREAD

**Issue by LJNeon** [GalAster/vscode-toml#1]
The VSCode extension only appears to support TOML 0.4.0, but here it appears to have TOML 1.0.0-rc.1 support.

**Comment by oovm** [comment]
Well, I've just published that new version, I studied the new standards and joined the formatting

There are not many new plans for the next step, so it may be left behind.

For my own I am using [TOML](https://marketplace.visualstudio.com/items?itemName=be5invis.toml) + [Even Better Toml](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) + [Crates](https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates)

![image](https://user-images.githubusercontent.com/17541209/86131009-a380f180-bb17-11ea-8758-674c80156957.png)

**Comment by LJNeon** [comment]
Fair enough, thanks!
