### ISSUE TITLE
TextMate Grammar

### ISSUE THREAD

**Issue by tamasfe** [GalAster/vscode-toml#2]
Hi, [Even Better TOML](https://github.com/tamasfe/taplo) badly needs a proper TOML grammar, and I was wondering if I could use yours in the future.

If yes, there are 2 questions to resolve:
- I would like to keep the MIT licence, but it is not compatible with MPL as far as I know. I'm not asking you to relicense the entire project, but rather to make an exception in this case.
- I'd like to add you to the contributors in the readme as the grammar would be a rather large addition.

**Comment by oovm** [comment]
This project was maintained by @be5invis many years ago.

I studied the new standard the previous year and took over the maintenance.

I am happy that someone can develop that further.

I'd like to relicense the grammar file and subsequent updates.

**Comment by tamasfe** [comment]
Awesome, thanks! I'll add a special thanks to both of you in the read me then, and will start porting the grammar in one of the following days.
