### ISSUE TITLE
Support for VSCode Web Extension

### ISSUE THREAD

**Issue by dufferzafar** [GalAster/vscode-toml#3]
VSCode now has Web Extensions which work in the web browser on sites like http://github.dev, http://vscode.dev or GitHub CodeSpaces.

Currently there are no .toml extensions that work in the browser.

![image](https://user-images.githubusercontent.com/1449512/140524181-765bd743-3901-46bb-b2db-d99b4fac1192.png)

I'm not sure how much of an effort it would be to enable the web extension support here, but just linking the docs here: https://code.visualstudio.com/api/extension-guides/web-extensions#update-existing-extensions-to-web-extensions

**Comment by dufferzafar** [comment]
The [enablement section of the documentation](https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-enablement) mentions that:

VS Code automatically treats an extension as a web extension if:

* The extension manifest (package.json) has browser entry point. 
* The extension manifest has no `main` entry point and none of the following contribution points: `localizations`, `debuggers`, `terminal`, `typescriptServerPlugins`.

Since this extension doesn't contribute anything from the above list, the only reason this isn't already working is because of the `main` entry point! Just removing that should work for now.

**Comment by oovm** [comment]
cc @be5invis , build new release with main entry point

**Comment by oovm** [comment]
cc @tamasfe, is it possible to call lsp from wasm-worker in VSCode Web?

**Comment by tamasfe** [comment]
> cc @tamasfe, is it possible to call lsp from wasm-worker in VSCode Web?

In theory the WASM LSP should work pretty much in every JS environment, it requires a JS shim for external things such as files, while the handlers must exist, none of them are required to do anything meaningful, and they can return mock responses (or probably even throw errors without any issues).
